// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function easeOutCubic(t) {
  return 1.0 - (1.0 - t) ** 3.0;
}

function easeInOutQuad(t) {
  if (t < 0.5) {
    return 2.0 * t * t;
  } else {
    return 1.0 - (-2.0 * t + 2.0) ** 2.0 / 2.0;
  }
}

let Easing = {
  easeOutCubic: easeOutCubic,
  easeInOutQuad: easeInOutQuad
};

let Types = {
  Easing: Easing
};

function castToElement(n) {
  if (n.nodeType === 1) {
    return Primitive_option.some(n);
  }
}

let DOM = {
  castToElement: castToElement
};

let Native = {};

let Observer = {};

let Mutation = {};

let Fetch = {};

let subscribers = {};

function subscribe(topic, cb) {
  let current = Stdlib_Option.getOr(subscribers[topic], []);
  subscribers[topic] = current.concat([cb]);
}

function publish(topic, payload) {
  let listeners = subscribers[topic];
  if (listeners !== undefined) {
    listeners.forEach(cb => cb(payload));
    return;
  }
}

let PubSub = {
  subscribers: subscribers,
  subscribe: subscribe,
  publish: publish
};

let connections = {};

function getOrCreate(url) {
  let ws = connections[url];
  if (ws !== undefined) {
    return Primitive_option.valFromOption(ws);
  }
  let ws$1 = new WebSocket(url);
  ws$1.addEventListener("message", evt => {
    let rawData = evt.data;
    try {
      let json = JSON.parse(rawData);
      let obj = Stdlib_JSON.Decode.object(json);
      if (obj === undefined) {
        return;
      }
      let match = obj["topic"];
      let match$1 = obj["html"];
      if (match === undefined) {
        return;
      }
      if (match$1 === undefined) {
        return;
      }
      let match$2 = Stdlib_JSON.Decode.string(match);
      let match$3 = Stdlib_JSON.Decode.string(match$1);
      if (match$2 !== undefined && match$3 !== undefined) {
        return publish(match$2, match$3);
      } else {
        return;
      }
    } catch (raw_exn) {
      let exn = Primitive_exceptions.internalToException(raw_exn);
      if (exn.RE_EXN_ID === "JsExn") {
        return;
      }
      throw exn;
    }
  });
  connections[url] = ws$1;
  return ws$1;
}

let WSManager = {
  connections: connections,
  getOrCreate: getOrCreate
};

let onRequestHooks = {
  contents: []
};

let onResponseHooks = {
  contents: []
};

function registerRequestHook(hook) {
  onRequestHooks.contents = onRequestHooks.contents.concat([hook]);
}

function registerResponseHook(hook) {
  onResponseHooks.contents = onResponseHooks.contents.concat([hook]);
}

function applyRequestPipeline(config) {
  return Stdlib_Array.reduce(onRequestHooks.contents, config, (cfg, hook) => hook(cfg));
}

function applyResponsePipeline(targetEl, rawHtml) {
  return Stdlib_Array.reduce(onResponseHooks.contents, rawHtml, (html, hook) => hook(targetEl, html));
}

let Middleware = {
  onRequestHooks: onRequestHooks,
  onResponseHooks: onResponseHooks,
  registerRequestHook: registerRequestHook,
  registerResponseHook: registerResponseHook,
  applyRequestPipeline: applyRequestPipeline,
  applyResponsePipeline: applyResponsePipeline
};

function getRect(el) {
  let raw = el.getBoundingClientRect();
  return {
    top: raw.top,
    left: raw.left,
    width: raw.width,
    height: raw.height
  };
}

function computeFlipDelta(first, last) {
  return {
    dx: first.left - last.left,
    dy: first.top - last.top,
    scaleX: last.width === 0.0 ? 1.0 : first.width / last.width,
    scaleY: last.height === 0.0 ? 1.0 : first.height / last.height
  };
}

function evalFlipStep(delta, t) {
  let decay = 1.0 - t;
  return [
    {
      x: delta.dx * decay,
      y: delta.dy * decay
    },
    {
      x: 1.0 + (delta.scaleX - 1.0) * decay,
      y: 1.0 + (delta.scaleY - 1.0) * decay
    }
  ];
}

function findLCP(s1, s2) {
  let len1 = s1.length;
  let len2 = s2.length;
  let limit = Math.min(len1, len2) | 0;
  let idx = 0;
  while (idx < limit && s1.charAt(idx) === s2.charAt(idx)) {
    idx = idx + 1 | 0;
  };
  return idx;
}

function computeStringDelta(source, target) {
  let lcp = findLCP(source, target);
  return {
    prefix: source.slice(0, lcp),
    remSource: source.slice(lcp, source.length),
    remTarget: target.slice(lcp, target.length)
  };
}

function evalStringDelta(delta, t) {
  let srcCut = Math.floor(delta.remSource.length * (1.0 - t)) | 0;
  let tgtAdd = Math.floor(delta.remTarget.length * t) | 0;
  let activeSource = delta.remSource.slice(0, srcCut);
  let activeTarget = delta.remTarget.slice(0, tgtAdd);
  return delta.prefix + activeSource + activeTarget;
}

function applyStep(targetEl, op, t) {
  if (typeof op !== "object") {
    return;
  }
  switch (op.TAG) {
    case "ScalarLerp" :
      let start = op.start;
      let currentVal = start + (op.target - start) * t;
      targetEl.setAttribute(op.attr, currentVal.toString());
      return;
    case "TextSplice" :
      let currentText = evalStringDelta(op.delta, t);
      let node = targetEl.firstChild;
      if (node !== undefined) {
        Primitive_option.valFromOption(node).nodeValue = currentText;
      } else {
        targetEl.setTextContent = currentText;
      }
      return;
    case "GeometryFlip" :
      let match = evalFlipStep(op._0, t);
      let scale = match[1];
      let pos = match[0];
      let styleStr = `transform: translate3d(` + pos.x.toString() + `px, ` + pos.y.toString() + `px, 0px) scale(` + scale.x.toString() + `, ` + scale.y.toString() + `); transform-origin: top left;`;
      targetEl.setAttribute("style", styleStr);
      return;
    case "Composite" :
      op._0.forEach(subOp => applyStep(targetEl, subOp, t));
      return;
  }
}

function animate(targetEl, op, durationOpt, easingOpt) {
  let duration = durationOpt !== undefined ? durationOpt : 300.0;
  let easing = easingOpt !== undefined ? easingOpt : easeOutCubic;
  let startTime = performance.now();
  let loop = _now => {
    let elapsed = performance.now() - startTime;
    let clampedProgress = Math.min(1.0, Math.max(0.0, elapsed / duration));
    let easedProgress = easing(clampedProgress);
    applyStep(targetEl, op, easedProgress);
    if (clampedProgress < 1.0) {
      requestAnimationFrame(loop);
    } else {
      targetEl.setAttribute("style", "");
    }
  };
  requestAnimationFrame(loop);
}

function swapOuterHTML(targetEl, newHtml, selector) {
  targetEl.outerHTML = newHtml;
  return document.querySelector(selector);
}

function morphOuterHTML(targetEl, newHtml, selector, durationOpt) {
  let duration = durationOpt !== undefined ? durationOpt : 300.0;
  let firstRect = getRect(targetEl);
  let newEl = swapOuterHTML(targetEl, newHtml, selector);
  if (newEl === undefined) {
    return;
  }
  let newEl$1 = Primitive_option.valFromOption(newEl);
  let lastRect = getRect(newEl$1);
  let delta = computeFlipDelta(firstRect, lastRect);
  animate(newEl$1, {
    TAG: "GeometryFlip",
    _0: delta
  }, duration, undefined);
}

function executeSwap(targetEl, htmlPayload, selector, swap) {
  let processedHtml = applyResponsePipeline(targetEl, htmlPayload);
  switch (swap) {
    case "OuterHTML" :
      return morphOuterHTML(targetEl, processedHtml, selector, undefined);
    case "InnerHTML" :
      targetEl.innerHTML = processedHtml;
      return;
    case "BeforeEnd" :
      targetEl.insertAdjacentHTML("beforeend", processedHtml);
      return;
  }
}

function getCsrfToken() {
  let el = document.querySelector("meta[name='csrf-token']");
  if (el !== undefined) {
    return Primitive_option.valFromOption(el).getAttribute("content");
  }
}

function parseHeaders(el) {
  let headers = {};
  headers["X-Hype-Request"] = "true";
  let token = getCsrfToken();
  if (token !== undefined) {
    headers["X-CSRF-Token"] = token;
  }
  let rawJson = el.getAttribute("hype-headers");
  if (rawJson !== undefined) {
    try {
      let parsed = JSON.parse(rawJson);
      let obj = Stdlib_JSON.Decode.object(parsed);
      if (obj !== undefined) {
        Object.keys(obj).forEach(k => {
          let v = obj[k];
          if (v === undefined) {
            return;
          }
          let strVal = Stdlib_JSON.Decode.string(v);
          if (strVal !== undefined) {
            headers[k] = strVal;
            return;
          }
        });
      }
    } catch (raw_exn) {
      let exn = Primitive_exceptions.internalToException(raw_exn);
      if (exn.RE_EXN_ID !== "JsExn") {
        throw exn;
      }
    }
  }
  return headers;
}

function parseVals(el) {
  let rawJson = el.getAttribute("hype-vals");
  if (rawJson === undefined) {
    return;
  }
  try {
    return JSON.parse(rawJson);
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return;
    }
    throw exn;
  }
}

function parseRequestConfig(el) {
  let verbAndUrl = el.getAttribute("hype-get") !== undefined ? Stdlib_Option.map(el.getAttribute("hype-get"), url => [
      "Get",
      url
    ]) : (
      el.getAttribute("hype-post") !== undefined ? Stdlib_Option.map(el.getAttribute("hype-post"), url => [
          "Post",
          url
        ]) : (
          el.getAttribute("hype-put") !== undefined ? Stdlib_Option.map(el.getAttribute("hype-put"), url => [
              "Put",
              url
            ]) : (
              el.getAttribute("hype-delete") !== undefined ? Stdlib_Option.map(el.getAttribute("hype-delete"), url => [
                  "Delete",
                  url
                ]) : (
                  el.getAttribute("hype-patch") !== undefined ? Stdlib_Option.map(el.getAttribute("hype-patch"), url => [
                      "Patch",
                      url
                    ]) : undefined
                )
            )
        )
    );
  if (verbAndUrl !== undefined) {
    return {
      verb: verbAndUrl[0],
      url: verbAndUrl[1],
      vals: parseVals(el),
      headers: parseHeaders(el)
    };
  }
}

function parseElementAction(el) {
  let triggerAttr = el.getAttribute("data-hype-on");
  let swapAttr = el.getAttribute("hype-swap");
  let wsUrl = el.getAttribute("hype-ws");
  let subTopic = el.getAttribute("hype-subscribe");
  let targetSelector = el.getAttribute("hype-target");
  let swapStrategy;
  if (swapAttr !== undefined) {
    switch (swapAttr) {
      case "beforeend" :
        swapStrategy = "BeforeEnd";
        break;
      case "outerHTML" :
        swapStrategy = "OuterHTML";
        break;
      default:
        swapStrategy = "InnerHTML";
    }
  } else {
    swapStrategy = "InnerHTML";
  }
  if (wsUrl !== undefined && subTopic !== undefined) {
    return {
      trigger: {
        TAG: "WebSocketMessage",
        url: Stdlib_Option.getOr(wsUrl, ""),
        topic: Stdlib_Option.getOr(subTopic, "")
      },
      targetSelector: targetSelector,
      request: undefined,
      swap: swapStrategy,
      op: "Identity"
    };
  }
  if (subTopic !== undefined) {
    return {
      trigger: {
        TAG: "PubSubTopic",
        _0: Stdlib_Option.getOr(subTopic, "")
      },
      targetSelector: targetSelector,
      request: undefined,
      swap: swapStrategy,
      op: "Identity"
    };
  }
  let request = parseRequestConfig(el);
  if (triggerAttr === "click") {
    return {
      trigger: "Click",
      targetSelector: targetSelector,
      request: request,
      swap: swapStrategy,
      op: "Identity"
    };
  }
}

function executeRequest(rawConfig, targetEl, selector, swap) {
  let config = applyRequestPipeline(rawConfig);
  let match = config.verb;
  let methodStr;
  switch (match) {
    case "Get" :
      methodStr = "GET";
      break;
    case "Post" :
      methodStr = "POST";
      break;
    case "Put" :
      methodStr = "PUT";
      break;
    case "Delete" :
      methodStr = "DELETE";
      break;
    case "Patch" :
      methodStr = "PATCH";
      break;
  }
  let json = config.vals;
  let fetchOpts = {
    method: methodStr,
    headers: config.headers,
    body: json !== undefined ? JSON.stringify(json) : undefined
  };
  fetch(config.url, fetchOpts).then(prim => prim.text()).then(html => {
    executeSwap(targetEl, html, selector, swap);
    return Promise.resolve();
  });
}

let globalIntersectionObserver = {
  contents: undefined
};

let globalMutationObserver = {
  contents: undefined
};

function bindElement(el) {
  let action = parseElementAction(el);
  if (action === undefined) {
    return;
  }
  let topic = action.trigger;
  if (typeof topic !== "object") {
    if (topic !== "Click") {
      return;
    }
    el.addEventListener("click", _evt => {
      let match = action.targetSelector;
      let match$1 = action.request;
      if (match === undefined) {
        return;
      }
      if (match$1 === undefined) {
        return;
      }
      let targetEl = document.querySelector(match);
      if (targetEl !== undefined) {
        return executeRequest(match$1, Primitive_option.valFromOption(targetEl), match, action.swap);
      }
    });
    return;
  } else {
    if (topic.TAG !== "WebSocketMessage") {
      return subscribe(topic._0, html => {
        let selector = action.targetSelector;
        if (selector === undefined) {
          return;
        }
        let targetEl = document.querySelector(selector);
        if (targetEl !== undefined) {
          return executeSwap(Primitive_option.valFromOption(targetEl), html, selector, action.swap);
        }
      });
    }
    getOrCreate(topic.url);
    return subscribe(topic.topic, html => {
      let selector = action.targetSelector;
      if (selector === undefined) {
        return;
      }
      let targetEl = document.querySelector(selector);
      if (targetEl !== undefined) {
        return executeSwap(Primitive_option.valFromOption(targetEl), html, selector, action.swap);
      }
    });
  }
}

function bootstrap(root) {
  if (globalIntersectionObserver.contents === undefined) {
    let obs = new IntersectionObserver(entries => {
      entries.forEach(entry => {
        if (!entry.isIntersecting) {
          return;
        }
        let el = entry.target;
        let config = parseRequestConfig(el);
        if (config === undefined) {
          return;
        }
        let selector = el.getAttribute("hype-target");
        if (selector === undefined) {
          return;
        }
        let targetEl = document.querySelector(selector);
        if (targetEl !== undefined) {
          return executeRequest(config, Primitive_option.valFromOption(targetEl), selector, "InnerHTML");
        }
      });
    });
    globalIntersectionObserver.contents = Primitive_option.some(obs);
  }
  if (root.matches("[data-hype-intersect='viewport']")) {
    let obs$1 = globalIntersectionObserver.contents;
    if (obs$1 !== undefined) {
      Primitive_option.valFromOption(obs$1).observe(root);
    }
  }
  let scrollTargets = root.querySelectorAll("[data-hype-intersect='viewport']");
  scrollTargets.forEach(el => {
    let obs = globalIntersectionObserver.contents;
    if (obs !== undefined) {
      Primitive_option.valFromOption(obs).observe(el);
      return;
    }
  });
  bindElement(root);
  let querySelectAndBind = selector => {
    root.querySelectorAll(selector).forEach(bindElement);
  };
  querySelectAndBind("[data-hype-on='click']");
  querySelectAndBind("[hype-ws]");
  querySelectAndBind("[hype-subscribe]");
}

function handleMutations(records) {
  records.forEach(record => {
    let nodes = record.addedNodes;
    nodes.forEach(node => {
      let element = castToElement(node);
      if (element !== undefined) {
        return bootstrap(Primitive_option.valFromOption(element));
      }
    });
  });
}

function initMutationWatcher() {
  if (globalMutationObserver.contents !== undefined) {
    return;
  }
  let observer = new MutationObserver(handleMutations);
  let options = { childList: true, subtree: true };
  observer.observe(document.body, options);
  globalMutationObserver.contents = Primitive_option.some(observer);
}

document.addEventListener("DOMContentLoaded", param => {
  bootstrap(document);
  initMutationWatcher();
});

export {
  Types,
  DOM,
  Native,
  Observer,
  Mutation,
  Fetch,
  PubSub,
  WSManager,
  Middleware,
  getRect,
  computeFlipDelta,
  evalFlipStep,
  findLCP,
  computeStringDelta,
  evalStringDelta,
  applyStep,
  animate,
  swapOuterHTML,
  morphOuterHTML,
  executeSwap,
  getCsrfToken,
  parseHeaders,
  parseVals,
  parseRequestConfig,
  parseElementAction,
  executeRequest,
  globalIntersectionObserver,
  globalMutationObserver,
  bindElement,
  bootstrap,
  handleMutations,
  initMutationWatcher,
}
/*  Not a pure module */
